# Generated by Django 4.1.4 on 2023-03-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
    ]
